# Generated by Django 4.2.7 on 2023-11-26 10:11

from django.db import migrations, models
import django.db.models.deletion
import inventory_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_app.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=50)),
                ("productCode", models.CharField(max_length=20)),
                ("productDescription", models.CharField(max_length=1000)),
                (
                    "productCategory",
                    models.CharField(
                        choices=[
                            ("Eyes", "Eyes"),
                            ("Face", "Face"),
                            ("Body Care", "Body Care"),
                            (
                                "Brushes and Beauty Blenders",
                                "Brushes and Beauty Blenders",
                            ),
                            ("Accessories", "Accessories"),
                            ("Kit", "Kit"),
                        ],
                        default="Eyes",
                        max_length=50,
                    ),
                ),
                (
                    "productImage",
                    models.ImageField(
                        null=True, upload_to=inventory_app.models.unique_img_name
                    ),
                ),
                ("productPrice", models.DecimalField(decimal_places=0, max_digits=5)),
                ("productQuantity", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["productCategory"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplierID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sales", "sales"), ("purchases", "purchases")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_app.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_app.product",
                    ),
                ),
            ],
        ),
    ]
