# Generated by Django 4.2.7 on 2023-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0002_customer_created_at_customer_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitAndLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchases", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_profit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
