# Generated by Django 4.2.7 on 2023-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0004_remove_product_productimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("sales", "Sales"), ("purchases", "Purchases")], max_length=20
            ),
        ),
    ]
